name: Auto-close Issues on Dev Merge

on:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  close-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:
      - name: Extract issue numbers and close them
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || "";
            const issueNumbers = [...prBody.matchAll(/(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)/gi)]
              .map(match => match[1]);

            for (const number of issueNumbers) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(number),
                state: "closed"
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(number),
                body: `✅ Automatically closed by PR [#${context.payload.pull_request.number}](${context.payload.pull_request.html_url}) merged into \`dev\`.`
              });
            }
